-- Bella v22 Resilience Lab
-- Safe Mode + privacy-minimal client error telemetry + stable persona experiments.

create table if not exists public.bella_resilience_config_v22 (
  id smallint primary key default 1 check (id = 1),
  safe_mode boolean not null default false,
  safe_mode_reason text not null default '',
  telemetry_enabled boolean not null default true,
  telemetry_sample_percent smallint not null default 50 check (telemetry_sample_percent between 0 and 100),
  revision integer not null default 1,
  updated_by uuid,
  updated_at timestamptz not null default now()
);

alter table public.bella_resilience_config_v22 enable row level security;
revoke all on table public.bella_resilience_config_v22 from anon, authenticated;

insert into public.bella_resilience_config_v22(id)
values (1)
on conflict (id) do nothing;

create table if not exists public.bella_experiments_v22 (
  experiment_key text primary key,
  kind text not null default 'persona' check (kind in ('persona')),
  label text not null default '',
  status text not null default 'draft' check (status in ('draft','running','paused','ended')),
  audience_percent smallint not null default 100 check (audience_percent between 0 and 100),
  variant_b_percent smallint not null default 50 check (variant_b_percent between 0 and 100),
  overlay_a text not null default '',
  overlay_b text not null default '',
  starts_at timestamptz,
  ends_at timestamptz,
  revision integer not null default 1,
  updated_by uuid,
  updated_at timestamptz not null default now(),
  constraint bella_experiments_v22_window_check check (ends_at is null or starts_at is null or ends_at > starts_at)
);

alter table public.bella_experiments_v22 enable row level security;
revoke all on table public.bella_experiments_v22 from anon, authenticated;
create index if not exists bella_experiments_v22_status_idx on public.bella_experiments_v22(status, starts_at, ends_at);

create table if not exists public.bella_client_events_v22 (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('boot_error','runtime_error','resource_error','api_error','network_error')),
  module text not null default '',
  fingerprint text not null,
  release text not null default '',
  route text not null default '',
  status_code integer,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.bella_client_events_v22 enable row level security;
revoke all on table public.bella_client_events_v22 from anon, authenticated;
create index if not exists bella_client_events_v22_created_idx on public.bella_client_events_v22(created_at desc);
create index if not exists bella_client_events_v22_fingerprint_idx on public.bella_client_events_v22(fingerprint, created_at desc);

create or replace function public.bella_public_resilience_v22(p_subject text default null)
returns table(safe_mode jsonb, experiment jsonb, telemetry jsonb)
language plpgsql stable security definer set search_path=''
as $$
declare
  cfg public.bella_resilience_config_v22%rowtype;
  exp public.bella_experiments_v22%rowtype;
  subject_key text;
  audience_bucket integer;
  variant_bucket integer;
  assigned_variant text := 'off';
  assigned_overlay text := '';
begin
  select * into cfg from public.bella_resilience_config_v22 where id=1;
  subject_key := coalesce(auth.uid()::text, nullif(left(trim(coalesce(p_subject,'')),120),''), 'anonymous');

  select * into exp
  from public.bella_experiments_v22 e
  where e.kind='persona'
    and e.status='running'
    and (e.starts_at is null or now() >= e.starts_at)
    and (e.ends_at is null or now() < e.ends_at)
  order by e.updated_at desc
  limit 1;

  if exp.experiment_key is not null then
    audience_bucket := abs(mod(pg_catalog.hashtextextended(subject_key || ':' || exp.experiment_key || ':audience', 22)::numeric, 100))::integer;
    if audience_bucket < exp.audience_percent then
      variant_bucket := abs(mod(pg_catalog.hashtextextended(subject_key || ':' || exp.experiment_key || ':variant', 23)::numeric, 100))::integer;
      if variant_bucket < exp.variant_b_percent then
        assigned_variant := 'b';
        assigned_overlay := exp.overlay_b;
      else
        assigned_variant := 'a';
        assigned_overlay := exp.overlay_a;
      end if;
    end if;
  end if;

  return query
  select
    jsonb_build_object(
      'enabled', coalesce(cfg.safe_mode,false),
      'public_message', case when coalesce(cfg.safe_mode,false) then 'وضع الاستقرار مفعّل مؤقتًا؛ بعض الميزات الثانوية متوقفة.' else '' end,
      'revision', coalesce(cfg.revision,1)
    ),
    case when exp.experiment_key is null then '{}'::jsonb else jsonb_build_object(
      'key', exp.experiment_key,
      'label', exp.label,
      'variant', assigned_variant,
      'overlay', case when assigned_variant in ('a','b') then left(assigned_overlay,1800) else '' end,
      'revision', exp.revision,
      'audience_percent', exp.audience_percent,
      'variant_b_percent', exp.variant_b_percent
    ) end,
    jsonb_build_object(
      'enabled', coalesce(cfg.telemetry_enabled,true),
      'sample_percent', coalesce(cfg.telemetry_sample_percent,50)
    );
end
$$;
revoke all on function public.bella_public_resilience_v22(text) from public;
grant execute on function public.bella_public_resilience_v22(text) to anon, authenticated;

create or replace function public.bella_record_client_event_v22(
  p_event_type text,
  p_module text,
  p_fingerprint text,
  p_release text default null,
  p_route text default null,
  p_status_code integer default null,
  p_detail jsonb default '{}'::jsonb
) returns boolean
language plpgsql security definer set search_path=''
as $$
declare
  cfg public.bella_resilience_config_v22%rowtype;
  et text:=lower(trim(coalesce(p_event_type,'')));
  fp text:=left(trim(coalesce(p_fingerprint,'')),96);
  safe_detail jsonb;
begin
  select * into cfg from public.bella_resilience_config_v22 where id=1;
  if not coalesce(cfg.telemetry_enabled,true) then return false; end if;
  if et not in ('boot_error','runtime_error','resource_error','api_error','network_error') then return false; end if;
  if length(fp) < 4 then return false; end if;
  if (select count(*) from public.bella_client_events_v22 where created_at > now() - interval '1 minute') >= 300 then return false; end if;
  if exists (
    select 1 from public.bella_client_events_v22
    where fingerprint=fp and event_type=et and created_at > now() - interval '60 seconds'
  ) then return false; end if;

  safe_detail := jsonb_strip_nulls(jsonb_build_object(
    'name', nullif(left(coalesce(p_detail->>'name',''),80),''),
    'phase', nullif(left(coalesce(p_detail->>'phase',''),80),''),
    'code', nullif(left(coalesce(p_detail->>'code',''),80),''),
    'source', nullif(left(coalesce(p_detail->>'source',''),120),''),
    'method', nullif(left(coalesce(p_detail->>'method',''),16),''),
    'kind', nullif(left(coalesce(p_detail->>'kind',''),48),''),
    'online', case when p_detail ? 'online' then to_jsonb((p_detail->>'online')::boolean) else null end,
    'visibility', nullif(left(coalesce(p_detail->>'visibility',''),24),'')
  ));

  insert into public.bella_client_events_v22(event_type,module,fingerprint,release,route,status_code,detail)
  values(
    et,
    left(trim(coalesce(p_module,'')),100),
    fp,
    left(trim(coalesce(p_release,'')),24),
    left(trim(coalesce(p_route,'')),160),
    case when p_status_code between 100 and 599 then p_status_code else null end,
    safe_detail
  );
  return true;
exception when invalid_text_representation then
  return false;
end
$$;
revoke all on function public.bella_record_client_event_v22(text,text,text,text,text,integer,jsonb) from public;
grant execute on function public.bella_record_client_event_v22(text,text,text,text,text,integer,jsonb) to anon, authenticated;

create or replace function public.bella_owner_set_safe_mode_v22(p_enabled boolean, p_reason text default null)
returns jsonb
language plpgsql security definer set search_path=''
as $$
declare
  actor uuid:=auth.uid();
  oldv jsonb;
  rowv jsonb;
begin
  if not public.is_bella_owner() then raise exception 'owner access required' using errcode='42501'; end if;
  select to_jsonb(c) into oldv from public.bella_resilience_config_v22 c where id=1 for update;
  update public.bella_resilience_config_v22
  set safe_mode=coalesce(p_enabled,false),
      safe_mode_reason=left(trim(coalesce(p_reason,'')),240),
      revision=revision+1,
      updated_by=actor,
      updated_at=now()
  where id=1
  returning to_jsonb(bella_resilience_config_v22) into rowv;
  insert into public.bella_admin_audit(actor_user_id,target_user_id,action,old_value,new_value,reason)
  values(actor,actor,'v22_safe_mode',coalesce(oldv,'{}'::jsonb),rowv,left(trim(coalesce(p_reason,'')),240));
  return rowv;
end
$$;
revoke all on function public.bella_owner_set_safe_mode_v22(boolean,text) from public,anon;
grant execute on function public.bella_owner_set_safe_mode_v22(boolean,text) to authenticated;

create or replace function public.bella_owner_set_telemetry_v22(p_enabled boolean, p_sample_percent integer default 50)
returns jsonb
language plpgsql security definer set search_path=''
as $$
declare
  actor uuid:=auth.uid();
  oldv jsonb;
  rowv jsonb;
  pct integer:=greatest(0,least(coalesce(p_sample_percent,50),100));
begin
  if not public.is_bella_owner() then raise exception 'owner access required' using errcode='42501'; end if;
  select to_jsonb(c) into oldv from public.bella_resilience_config_v22 c where id=1 for update;
  update public.bella_resilience_config_v22
  set telemetry_enabled=coalesce(p_enabled,false),
      telemetry_sample_percent=pct,
      revision=revision+1,
      updated_by=actor,
      updated_at=now()
  where id=1
  returning to_jsonb(bella_resilience_config_v22) into rowv;
  insert into public.bella_admin_audit(actor_user_id,target_user_id,action,old_value,new_value,reason)
  values(actor,actor,'v22_telemetry',coalesce(oldv,'{}'::jsonb),rowv,'Resilience Lab v22 telemetry setting');
  return rowv;
end
$$;
revoke all on function public.bella_owner_set_telemetry_v22(boolean,integer) from public,anon;
grant execute on function public.bella_owner_set_telemetry_v22(boolean,integer) to authenticated;

create or replace function public.bella_owner_upsert_experiment_v22(
  p_key text,
  p_label text,
  p_status text,
  p_audience_percent integer,
  p_variant_b_percent integer,
  p_overlay_a text default '',
  p_overlay_b text default '',
  p_start timestamptz default null,
  p_end timestamptz default null,
  p_reason text default null
) returns jsonb
language plpgsql security definer set search_path=''
as $$
declare
  actor uuid:=auth.uid();
  k text:=lower(trim(coalesce(p_key,'')));
  st text:=lower(trim(coalesce(p_status,'draft')));
  oldv jsonb;
  rowv jsonb;
  aud integer:=greatest(0,least(coalesce(p_audience_percent,100),100));
  vb integer:=greatest(0,least(coalesce(p_variant_b_percent,50),100));
begin
  if not public.is_bella_owner() then raise exception 'owner access required' using errcode='42501'; end if;
  if k !~ '^[a-z0-9][a-z0-9_-]{0,39}$' then raise exception 'invalid experiment key' using errcode='22023'; end if;
  if st not in ('draft','running','paused','ended') then raise exception 'invalid experiment status' using errcode='22023'; end if;
  if p_end is not null and p_start is not null and p_end <= p_start then raise exception 'experiment end must be after start' using errcode='22023'; end if;

  select to_jsonb(e) into oldv from public.bella_experiments_v22 e where e.experiment_key=k for update;
  if st='running' then
    update public.bella_experiments_v22
    set status='paused',updated_by=actor,updated_at=now(),revision=revision+1
    where kind='persona' and status='running' and experiment_key<>k;
  end if;

  insert into public.bella_experiments_v22(
    experiment_key,kind,label,status,audience_percent,variant_b_percent,overlay_a,overlay_b,starts_at,ends_at,updated_by,updated_at
  ) values (
    k,'persona',left(trim(coalesce(p_label,'')),80),st,aud,vb,left(trim(coalesce(p_overlay_a,'')),1800),left(trim(coalesce(p_overlay_b,'')),1800),p_start,p_end,actor,now()
  )
  on conflict (experiment_key) do update set
    label=excluded.label,
    status=excluded.status,
    audience_percent=excluded.audience_percent,
    variant_b_percent=excluded.variant_b_percent,
    overlay_a=excluded.overlay_a,
    overlay_b=excluded.overlay_b,
    starts_at=excluded.starts_at,
    ends_at=excluded.ends_at,
    revision=public.bella_experiments_v22.revision+1,
    updated_by=actor,
    updated_at=now()
  returning to_jsonb(bella_experiments_v22) into rowv;

  insert into public.bella_admin_audit(actor_user_id,target_user_id,action,old_value,new_value,reason)
  values(actor,actor,'v22_experiment_upsert',coalesce(oldv,'{}'::jsonb),rowv,left(trim(coalesce(p_reason,'')),240));
  return rowv;
end
$$;
revoke all on function public.bella_owner_upsert_experiment_v22(text,text,text,integer,integer,text,text,timestamptz,timestamptz,text) from public,anon;
grant execute on function public.bella_owner_upsert_experiment_v22(text,text,text,integer,integer,text,text,timestamptz,timestamptz,text) to authenticated;

create or replace function public.bella_owner_prune_events_v22(p_keep_days integer default 14)
returns integer
language plpgsql security definer set search_path=''
as $$
declare
  actor uuid:=auth.uid();
  days_to_keep integer:=greatest(1,least(coalesce(p_keep_days,14),90));
  deleted_count integer;
begin
  if not public.is_bella_owner() then raise exception 'owner access required' using errcode='42501'; end if;
  delete from public.bella_client_events_v22 where created_at < now() - make_interval(days=>days_to_keep);
  get diagnostics deleted_count = row_count;
  insert into public.bella_admin_audit(actor_user_id,target_user_id,action,old_value,new_value,reason)
  values(actor,actor,'v22_event_prune','{}'::jsonb,jsonb_build_object('deleted',deleted_count,'keep_days',days_to_keep),'Resilience Lab v22 event retention');
  return deleted_count;
end
$$;
revoke all on function public.bella_owner_prune_events_v22(integer) from public,anon;
grant execute on function public.bella_owner_prune_events_v22(integer) to authenticated;

create or replace function public.bella_owner_resilience_v22(p_event_limit integer default 40)
returns table(resilience_config jsonb, experiments jsonb, event_summary jsonb, latest_events jsonb)
language plpgsql stable security definer set search_path=''
as $$
declare
  lim integer:=greatest(1,least(coalesce(p_event_limit,40),100));
begin
  if not public.is_bella_owner() then raise exception 'owner access required' using errcode='42501'; end if;
  return query
  select
    coalesce((select to_jsonb(c) from public.bella_resilience_config_v22 c where c.id=1),'{}'::jsonb),
    coalesce((select jsonb_agg(to_jsonb(e) order by e.updated_at desc) from public.bella_experiments_v22 e),'[]'::jsonb),
    coalesce((select jsonb_agg(jsonb_build_object(
      'event_type',x.event_type,
      'module',x.module,
      'count',x.event_count,
      'last_seen',x.last_seen
    ) order by x.event_count desc,x.last_seen desc)
      from (
        select ce.event_type,ce.module,count(*)::bigint event_count,max(ce.created_at) last_seen
        from public.bella_client_events_v22 ce
        where ce.created_at > now() - interval '24 hours'
        group by ce.event_type,ce.module
        order by count(*) desc,max(ce.created_at) desc
        limit 30
      ) x),'[]'::jsonb),
    coalesce((select jsonb_agg(to_jsonb(y) order by y.created_at desc)
      from (
        select ce.id,ce.event_type,ce.module,ce.fingerprint,ce.release,ce.route,ce.status_code,ce.detail,ce.created_at
        from public.bella_client_events_v22 ce
        order by ce.created_at desc
        limit lim
      ) y),'[]'::jsonb);
end
$$;
revoke all on function public.bella_owner_resilience_v22(integer) from public,anon;
grant execute on function public.bella_owner_resilience_v22(integer) to authenticated;
