alter table public.bella_app_config
  add column if not exists emergency_lockdown boolean not null default false,
  add column if not exists lockdown_message text not null default 'بيلا تحت الصيانة الطارئة مؤقتًا 🛠️',
  add column if not exists lockdown_snapshot jsonb not null default '{}'::jsonb,
  add column if not exists scheduled_maintenance_start timestamptz,
  add column if not exists scheduled_maintenance_end timestamptz,
  add column if not exists scheduled_maintenance_message text not null default '',
  add column if not exists scheduled_announcement text not null default '',
  add column if not exists scheduled_announcement_start timestamptz,
  add column if not exists scheduled_announcement_end timestamptz;

alter table public.bella_account_admin
  add column if not exists suspended_until timestamptz,
  add column if not exists suspension_type text not null default 'none';

do $$ begin
  if not exists (select 1 from pg_constraint where conname='bella_account_admin_suspension_type_check') then
    alter table public.bella_account_admin add constraint bella_account_admin_suspension_type_check check (suspension_type in ('none','temporary','permanent'));
  end if;
end $$;

create table if not exists public.bella_broadcasts (
  id bigint generated by default as identity primary key,
  title text not null default '', message text not null,
  level text not null default 'info' check (level in ('info','success','warning','urgent')),
  enabled boolean not null default true,
  starts_at timestamptz not null default now(), expires_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index if not exists bella_broadcasts_active_idx on public.bella_broadcasts(enabled,starts_at,expires_at);
alter table public.bella_broadcasts enable row level security;
drop policy if exists bella_broadcasts_public_select on public.bella_broadcasts;
create policy bella_broadcasts_public_select on public.bella_broadcasts for select to anon,authenticated using (enabled=true and starts_at<=now() and (expires_at is null or expires_at>now()));
drop policy if exists bella_broadcasts_owner_all on public.bella_broadcasts;
create policy bella_broadcasts_owner_all on public.bella_broadcasts for all to authenticated using (public.is_bella_owner()) with check (public.is_bella_owner());

create table if not exists public.bella_user_gifts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  gift_type text not null default 'gift' check (gift_type in ('gift','xp','bonus')),
  label text not null default 'هدية من بيلا 🎁', message text not null default '',
  xp_amount integer not null default 0 check (xp_amount between 0 and 10000),
  viewed_at timestamptz, created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists bella_user_gifts_user_idx on public.bella_user_gifts(user_id,created_at desc);
alter table public.bella_user_gifts enable row level security;
drop policy if exists bella_user_gifts_self_select on public.bella_user_gifts;
create policy bella_user_gifts_self_select on public.bella_user_gifts for select to authenticated using (user_id=auth.uid() or public.is_bella_owner());
drop policy if exists bella_user_gifts_self_update on public.bella_user_gifts;
create policy bella_user_gifts_self_update on public.bella_user_gifts for update to authenticated using (user_id=auth.uid() or public.is_bella_owner()) with check (user_id=auth.uid() or public.is_bella_owner());
drop policy if exists bella_user_gifts_owner_insert on public.bella_user_gifts;
create policy bella_user_gifts_owner_insert on public.bella_user_gifts for insert to authenticated with check (public.is_bella_owner());
drop policy if exists bella_user_gifts_owner_delete on public.bella_user_gifts;
create policy bella_user_gifts_owner_delete on public.bella_user_gifts for delete to authenticated using (public.is_bella_owner());

create or replace function public.bella_is_account_active() returns boolean language sql stable security definer set search_path='' as $$
  select case when auth.uid() is null then false else coalesce((select case when a.account_status<>'suspended' then true when a.suspension_type='temporary' and a.suspended_until is not null and a.suspended_until<=now() then true else false end from public.bella_account_admin a where a.user_id=auth.uid()),true) end;
$$;

create or replace function public.bella_account_status() returns table(account_status text,staff_role text,suspended_reason text) language sql stable security definer set search_path='' as $$
  select case when coalesce(a.account_status,'active')='suspended' and a.suspension_type='temporary' and a.suspended_until is not null and a.suspended_until<=now() then 'active' else coalesce(a.account_status,'active') end::text,
         coalesce(a.staff_role,'user')::text,
         case when coalesce(a.account_status,'active')='suspended' and not (a.suspension_type='temporary' and a.suspended_until is not null and a.suspended_until<=now()) then a.suspended_reason else null end::text
  from (select auth.uid() uid) me left join public.bella_account_admin a on a.user_id=me.uid where me.uid is not null;
$$;

create or replace function public.bella_account_status_v2() returns table(account_status text,staff_role text,suspended_reason text,suspended_until timestamptz,suspension_type text) language sql stable security definer set search_path='' as $$
  select case when coalesce(a.account_status,'active')='suspended' and a.suspension_type='temporary' and a.suspended_until is not null and a.suspended_until<=now() then 'active' else coalesce(a.account_status,'active') end::text,
         coalesce(a.staff_role,'user')::text,
         case when coalesce(a.account_status,'active')='suspended' and not (a.suspension_type='temporary' and a.suspended_until is not null and a.suspended_until<=now()) then a.suspended_reason else null end::text,
         case when coalesce(a.account_status,'active')='suspended' then a.suspended_until else null end,
         case when coalesce(a.account_status,'active')='suspended' then coalesce(a.suspension_type,'permanent') else 'none' end::text
  from (select auth.uid() uid) me left join public.bella_account_admin a on a.user_id=me.uid where me.uid is not null;
$$;
revoke all on function public.bella_account_status_v2() from public,anon; grant execute on function public.bella_account_status_v2() to authenticated;

create or replace function public.bella_owner_set_ban(p_user_id uuid,p_minutes integer default null,p_permanent boolean default false,p_reason text default null)
returns table(account_status text,suspension_type text,suspended_until timestamptz,suspended_reason text)
language plpgsql security definer set search_path='' as $$
declare actor uuid:=auth.uid(); mins integer:=greatest(1,least(coalesce(p_minutes,60),525600)); why text:=nullif(left(trim(coalesce(p_reason,'')),240),''); oldv jsonb; untilv timestamptz;
begin
  if not public.is_bella_owner() then raise exception 'owner access required' using errcode='42501'; end if;
  if p_user_id is null or not exists(select 1 from public.bella_profiles p where p.user_id=p_user_id) then raise exception 'user not found' using errcode='22023'; end if;
  if exists(select 1 from public.bella_owner_singleton o where o.slot=1 and o.user_id=p_user_id) then raise exception 'owner account cannot be banned' using errcode='42501'; end if;
  insert into public.bella_account_admin(user_id) values(p_user_id) on conflict(user_id) do nothing;
  select jsonb_build_object('account_status',account_status,'suspension_type',suspension_type,'suspended_until',suspended_until,'reason',suspended_reason) into oldv from public.bella_account_admin where user_id=p_user_id for update;
  untilv:=case when coalesce(p_permanent,false) then null else now()+make_interval(mins=>mins) end;
  update public.bella_account_admin set account_status='suspended',suspended_at=now(),suspended_until=untilv,suspension_type=case when coalesce(p_permanent,false) then 'permanent' else 'temporary' end,suspended_reason=why,updated_at=now() where user_id=p_user_id;
  insert into public.bella_admin_audit(actor_user_id,target_user_id,action,old_value,new_value,reason) values(actor,p_user_id,case when coalesce(p_permanent,false) then 'ban_permanent' else 'ban_temporary' end,coalesce(oldv,'{}'::jsonb),jsonb_build_object('suspended_until',untilv,'minutes',case when coalesce(p_permanent,false) then null else mins end),why);
  return query select a.account_status,a.suspension_type,a.suspended_until,a.suspended_reason from public.bella_account_admin a where a.user_id=p_user_id;
end $$;

create or replace function public.bella_owner_unban(p_user_id uuid,p_reason text default null) returns boolean language plpgsql security definer set search_path='' as $$
declare actor uuid:=auth.uid(); why text:=nullif(left(trim(coalesce(p_reason,'')),240),''); oldv jsonb;
begin
  if not public.is_bella_owner() then raise exception 'owner access required' using errcode='42501'; end if;
  if exists(select 1 from public.bella_owner_singleton o where o.slot=1 and o.user_id=p_user_id) then raise exception 'owner account cannot be modified' using errcode='42501'; end if;
  insert into public.bella_account_admin(user_id) values(p_user_id) on conflict(user_id) do nothing;
  select jsonb_build_object('account_status',account_status,'suspension_type',suspension_type,'suspended_until',suspended_until,'reason',suspended_reason) into oldv from public.bella_account_admin where user_id=p_user_id for update;
  update public.bella_account_admin set account_status='active',suspended_at=null,suspended_until=null,suspension_type='none',suspended_reason=null,updated_at=now() where user_id=p_user_id;
  insert into public.bella_admin_audit(actor_user_id,target_user_id,action,old_value,new_value,reason) values(actor,p_user_id,'unban',coalesce(oldv,'{}'::jsonb),jsonb_build_object('account_status','active'),why);
  return true;
end $$;

create or replace function public.bella_owner_set_progress(p_user_id uuid,p_xp integer,p_level integer,p_reason text default null)
returns table(xp integer,level integer) language plpgsql security definer set search_path='' as $$
declare actor uuid:=auth.uid(); nxp integer:=greatest(0,least(coalesce(p_xp,0),1000000)); nlevel integer:=greatest(1,least(coalesce(p_level,1),10000)); oldv jsonb; why text:=nullif(left(trim(coalesce(p_reason,'')),240),'');
begin
  if not public.is_bella_owner() then raise exception 'owner access required' using errcode='42501'; end if;
  if exists(select 1 from public.bella_owner_singleton o where o.slot=1 and o.user_id=p_user_id) then raise exception 'owner account cannot be modified here' using errcode='42501'; end if;
  select jsonb_build_object('xp',p.xp,'level',p.level) into oldv from public.bella_profiles p where p.user_id=p_user_id for update;
  if oldv is null then raise exception 'user not found' using errcode='22023'; end if;
  update public.bella_profiles set xp=nxp,level=nlevel,updated_at=now() where user_id=p_user_id;
  insert into public.bella_admin_audit(actor_user_id,target_user_id,action,old_value,new_value,reason) values(actor,p_user_id,'set_progress',oldv,jsonb_build_object('xp',nxp,'level',nlevel),why);
  return query select nxp,nlevel;
end $$;

create or replace function public.bella_owner_adjust_xp(p_user_id uuid,p_delta integer,p_reason text default null)
returns table(xp integer,level integer) language plpgsql security definer set search_path='' as $$
declare actor uuid:=auth.uid(); delta integer:=greatest(-50000,least(coalesce(p_delta,0),50000)); oldxp integer; newxp integer; newlevel integer; why text:=nullif(left(trim(coalesce(p_reason,'')),240),'');
begin
  if not public.is_bella_owner() then raise exception 'owner access required' using errcode='42501'; end if;
  if exists(select 1 from public.bella_owner_singleton o where o.slot=1 and o.user_id=p_user_id) then raise exception 'owner account cannot be modified here' using errcode='42501'; end if;
  select p.xp into oldxp from public.bella_profiles p where p.user_id=p_user_id for update;
  if oldxp is null then raise exception 'user not found' using errcode='22023'; end if;
  newxp:=greatest(0,least(oldxp+delta,1000000)); newlevel:=greatest(1,floor(newxp/100.0)::integer+1);
  update public.bella_profiles set xp=newxp,level=newlevel,updated_at=now() where user_id=p_user_id;
  insert into public.bella_admin_audit(actor_user_id,target_user_id,action,old_value,new_value,reason) values(actor,p_user_id,'adjust_xp',jsonb_build_object('xp',oldxp),jsonb_build_object('xp',newxp,'delta',delta,'level',newlevel),why);
  return query select newxp,newlevel;
end $$;

create or replace function public.bella_owner_schedule_maintenance(p_start timestamptz,p_end timestamptz,p_message text default null) returns boolean language plpgsql security definer set search_path='' as $$
declare actor uuid:=auth.uid(); msg text:=left(trim(coalesce(p_message,'')),500);
begin if not public.is_bella_owner() then raise exception 'owner access required' using errcode='42501'; end if; if p_start is null or p_end is null or p_end<=p_start then raise exception 'invalid schedule' using errcode='22023'; end if; update public.bella_app_config set scheduled_maintenance_start=p_start,scheduled_maintenance_end=p_end,scheduled_maintenance_message=msg,updated_at=now(),updated_by=actor where id=1; insert into public.bella_admin_audit(actor_user_id,target_user_id,action,old_value,new_value,reason) values(actor,actor,'schedule_maintenance','{}'::jsonb,jsonb_build_object('start',p_start,'end',p_end,'message',msg),null); return true; end $$;

create or replace function public.bella_owner_schedule_announcement(p_text text,p_start timestamptz,p_end timestamptz) returns boolean language plpgsql security definer set search_path='' as $$
declare actor uuid:=auth.uid(); msg text:=left(trim(coalesce(p_text,'')),500);
begin if not public.is_bella_owner() then raise exception 'owner access required' using errcode='42501'; end if; if msg='' or p_start is null or p_end is null or p_end<=p_start then raise exception 'invalid schedule' using errcode='22023'; end if; update public.bella_app_config set scheduled_announcement=msg,scheduled_announcement_start=p_start,scheduled_announcement_end=p_end,updated_at=now(),updated_by=actor where id=1; insert into public.bella_admin_audit(actor_user_id,target_user_id,action,old_value,new_value,reason) values(actor,actor,'schedule_announcement','{}'::jsonb,jsonb_build_object('start',p_start,'end',p_end,'text',msg),null); return true; end $$;

create or replace function public.bella_owner_clear_schedule(p_kind text) returns boolean language plpgsql security definer set search_path='' as $$
declare actor uuid:=auth.uid(); k text:=lower(trim(coalesce(p_kind,'')));
begin if not public.is_bella_owner() then raise exception 'owner access required' using errcode='42501'; end if; if k='maintenance' then update public.bella_app_config set scheduled_maintenance_start=null,scheduled_maintenance_end=null,scheduled_maintenance_message='',updated_at=now(),updated_by=actor where id=1; elsif k='announcement' then update public.bella_app_config set scheduled_announcement='',scheduled_announcement_start=null,scheduled_announcement_end=null,updated_at=now(),updated_by=actor where id=1; else raise exception 'invalid schedule kind' using errcode='22023'; end if; insert into public.bella_admin_audit(actor_user_id,target_user_id,action,old_value,new_value,reason) values(actor,actor,'clear_schedule','{}'::jsonb,jsonb_build_object('kind',k),null); return true; end $$;

create or replace function public.bella_owner_create_broadcast(p_title text,p_message text,p_level text default 'info',p_start timestamptz default now(),p_end timestamptz default null) returns bigint language plpgsql security definer set search_path='' as $$
declare actor uuid:=auth.uid(); bid bigint; lvl text:=lower(trim(coalesce(p_level,'info'))); titlev text:=left(trim(coalesce(p_title,'')),120); msg text:=left(trim(coalesce(p_message,'')),800);
begin if not public.is_bella_owner() then raise exception 'owner access required' using errcode='42501'; end if; if lvl not in ('info','success','warning','urgent') then lvl:='info'; end if; if msg='' then raise exception 'message required' using errcode='22023'; end if; if p_end is not null and p_end<=coalesce(p_start,now()) then raise exception 'invalid broadcast schedule' using errcode='22023'; end if; insert into public.bella_broadcasts(title,message,level,enabled,starts_at,expires_at,created_by) values(titlev,msg,lvl,true,coalesce(p_start,now()),p_end,actor) returning id into bid; insert into public.bella_admin_audit(actor_user_id,target_user_id,action,old_value,new_value,reason) values(actor,actor,'create_broadcast','{}'::jsonb,jsonb_build_object('id',bid,'level',lvl,'starts_at',coalesce(p_start,now()),'expires_at',p_end),null); return bid; end $$;

create or replace function public.bella_public_broadcasts() returns table(id bigint,title text,message text,level text,starts_at timestamptz,expires_at timestamptz) language sql stable security definer set search_path='' as $$ select b.id,b.title,b.message,b.level,b.starts_at,b.expires_at from public.bella_broadcasts b where b.enabled=true and b.starts_at<=now() and (b.expires_at is null or b.expires_at>now()) order by case b.level when 'urgent' then 0 when 'warning' then 1 else 2 end,b.created_at desc limit 5 $$;

create or replace function public.bella_owner_send_gift(p_user_id uuid,p_label text,p_message text default null,p_xp integer default 0) returns bigint language plpgsql security definer set search_path='' as $$
declare actor uuid:=auth.uid(); gid bigint; amount integer:=greatest(0,least(coalesce(p_xp,0),10000)); labelv text:=left(trim(coalesce(p_label,'هدية من بيلا 🎁')),120); msg text:=left(trim(coalesce(p_message,'')),500); oldxp integer; newxp integer; newlevel integer;
begin if not public.is_bella_owner() then raise exception 'owner access required' using errcode='42501'; end if; if p_user_id is null or not exists(select 1 from public.bella_profiles p where p.user_id=p_user_id) then raise exception 'user not found' using errcode='22023'; end if; select xp into oldxp from public.bella_profiles where user_id=p_user_id for update; newxp:=greatest(0,least(coalesce(oldxp,0)+amount,1000000)); newlevel:=greatest(1,floor(newxp/100.0)::integer+1); insert into public.bella_user_gifts(user_id,gift_type,label,message,xp_amount,created_by) values(p_user_id,case when amount>0 then 'xp' else 'gift' end,labelv,msg,amount,actor) returning id into gid; update public.bella_profiles set xp=newxp,level=greatest(level,newlevel),gifts=gifts+1,updated_at=now() where user_id=p_user_id; insert into public.bella_admin_audit(actor_user_id,target_user_id,action,old_value,new_value,reason) values(actor,p_user_id,'send_gift',jsonb_build_object('xp',oldxp),jsonb_build_object('gift_id',gid,'xp',newxp,'amount',amount,'label',labelv),msg); return gid; end $$;

create or replace function public.bella_my_gifts(p_limit integer default 10) returns table(id bigint,label text,message text,xp_amount integer,viewed_at timestamptz,created_at timestamptz) language sql stable security definer set search_path='' as $$ select g.id,g.label,g.message,g.xp_amount,g.viewed_at,g.created_at from public.bella_user_gifts g where g.user_id=auth.uid() order by g.created_at desc limit greatest(1,least(coalesce(p_limit,10),25)) $$;
create or replace function public.bella_mark_gift_viewed(p_id bigint) returns boolean language plpgsql security definer set search_path='' as $$ begin if auth.uid() is null then return false; end if; update public.bella_user_gifts set viewed_at=coalesce(viewed_at,now()) where id=p_id and user_id=auth.uid(); return found; end $$;

create or replace function public.bella_owner_kill_switch(p_enable boolean,p_message text default null) returns boolean language plpgsql security definer set search_path='' as $$
declare actor uuid:=auth.uid(); snap jsonb; msg text:=left(trim(coalesce(p_message,'بيلا تحت الصيانة الطارئة مؤقتًا 🛠️')),500);
begin if not public.is_bella_owner() then raise exception 'owner access required' using errcode='42501'; end if; select lockdown_snapshot into snap from public.bella_app_config where id=1 for update; if coalesce(p_enable,false) then update public.bella_app_config set lockdown_snapshot=jsonb_build_object('live_web_enabled',live_web_enabled,'games_enabled',games_enabled,'radar_enabled',radar_enabled,'maintenance_enabled',maintenance_enabled,'leaderboard_enabled',leaderboard_enabled,'content_ai_enabled',content_ai_enabled,'wisdom_game_enabled',wisdom_game_enabled,'proverb_game_enabled',proverb_game_enabled,'rumor_list_enabled',rumor_list_enabled,'box_game_enabled',box_game_enabled,'kuwait_quiz_enabled',kuwait_quiz_enabled,'chat_ai_enabled',chat_ai_enabled,'voice_enabled',voice_enabled,'ai_activities_enabled',ai_activities_enabled,'moments_enabled',moments_enabled),emergency_lockdown=true,lockdown_message=msg,maintenance_enabled=true,live_web_enabled=false,games_enabled=false,radar_enabled=false,leaderboard_enabled=false,content_ai_enabled=false,wisdom_game_enabled=false,proverb_game_enabled=false,rumor_list_enabled=false,box_game_enabled=false,kuwait_quiz_enabled=false,chat_ai_enabled=false,voice_enabled=false,ai_activities_enabled=false,moments_enabled=false,updated_at=now(),updated_by=actor where id=1; else update public.bella_app_config set emergency_lockdown=false,live_web_enabled=coalesce((snap->>'live_web_enabled')::boolean,live_web_enabled),games_enabled=coalesce((snap->>'games_enabled')::boolean,games_enabled),radar_enabled=coalesce((snap->>'radar_enabled')::boolean,radar_enabled),maintenance_enabled=coalesce((snap->>'maintenance_enabled')::boolean,false),leaderboard_enabled=coalesce((snap->>'leaderboard_enabled')::boolean,leaderboard_enabled),content_ai_enabled=coalesce((snap->>'content_ai_enabled')::boolean,content_ai_enabled),wisdom_game_enabled=coalesce((snap->>'wisdom_game_enabled')::boolean,wisdom_game_enabled),proverb_game_enabled=coalesce((snap->>'proverb_game_enabled')::boolean,proverb_game_enabled),rumor_list_enabled=coalesce((snap->>'rumor_list_enabled')::boolean,rumor_list_enabled),box_game_enabled=coalesce((snap->>'box_game_enabled')::boolean,box_game_enabled),kuwait_quiz_enabled=coalesce((snap->>'kuwait_quiz_enabled')::boolean,kuwait_quiz_enabled),chat_ai_enabled=coalesce((snap->>'chat_ai_enabled')::boolean,chat_ai_enabled),voice_enabled=coalesce((snap->>'voice_enabled')::boolean,voice_enabled),ai_activities_enabled=coalesce((snap->>'ai_activities_enabled')::boolean,ai_activities_enabled),moments_enabled=coalesce((snap->>'moments_enabled')::boolean,moments_enabled),lockdown_snapshot='{}'::jsonb,updated_at=now(),updated_by=actor where id=1; end if; insert into public.bella_admin_audit(actor_user_id,target_user_id,action,old_value,new_value,reason) values(actor,actor,case when coalesce(p_enable,false) then 'kill_switch_on' else 'kill_switch_off' end,coalesce(snap,'{}'::jsonb),jsonb_build_object('enabled',coalesce(p_enable,false),'message',msg),null); return coalesce(p_enable,false); end $$;

create or replace function public.bella_owner_ops_state() returns table(emergency_lockdown boolean,lockdown_message text,scheduled_maintenance_start timestamptz,scheduled_maintenance_end timestamptz,scheduled_maintenance_message text,scheduled_announcement text,scheduled_announcement_start timestamptz,scheduled_announcement_end timestamptz,active_broadcasts bigint,active_temp_bans bigint,permanent_bans bigint,gifts_today bigint,today_ai_used integer,pending_content bigint) language plpgsql stable security definer set search_path='' as $$ begin if not public.is_bella_owner() then raise exception 'owner access required' using errcode='42501'; end if; return query select c.emergency_lockdown,c.lockdown_message,c.scheduled_maintenance_start,c.scheduled_maintenance_end,c.scheduled_maintenance_message,c.scheduled_announcement,c.scheduled_announcement_start,c.scheduled_announcement_end,(select count(*) from public.bella_broadcasts b where b.enabled and b.starts_at<=now() and (b.expires_at is null or b.expires_at>now())),(select count(*) from public.bella_account_admin a where a.account_status='suspended' and a.suspension_type='temporary' and a.suspended_until>now()),(select count(*) from public.bella_account_admin a where a.account_status='suspended' and a.suspension_type='permanent'),(select count(*) from public.bella_user_gifts g where g.created_at>=current_date),coalesce(u.requests,0),(select count(*) from public.bella_content_items x where x.status='pending') from public.bella_app_config c left join public.bella_ai_daily_usage u on u.usage_day=current_date where c.id=1; end $$;

create or replace function public.bella_owner_dashboard_v4(p_days integer default 30) returns table(total_accounts bigint,new_today bigint,new_7d bigint,active_today bigint,active_7d bigint,suspended_active bigint,temp_bans bigint,permanent_bans bigint,total_game_sessions bigint,total_game_correct bigint,total_game_answers bigint,game_accuracy numeric,ai_used_today integer,active_broadcasts bigint,gifts_today bigint,pending_content bigint,approved_content bigint) language plpgsql stable security definer set search_path='' as $$ begin if not public.is_bella_owner() then raise exception 'owner access required' using errcode='42501'; end if; return query select (select count(*) from public.bella_profiles),(select count(*) from public.bella_profiles p where p.created_at>=current_date),(select count(*) from public.bella_profiles p where p.created_at>=now()-interval '7 days'),(select count(distinct e.user_id) from public.bella_events e where e.created_at>=current_date),(select count(distinct e.user_id) from public.bella_events e where e.created_at>=now()-interval '7 days'),(select count(*) from public.bella_account_admin a where a.account_status='suspended' and not (a.suspension_type='temporary' and a.suspended_until<=now())),(select count(*) from public.bella_account_admin a where a.account_status='suspended' and a.suspension_type='temporary' and a.suspended_until>now()),(select count(*) from public.bella_account_admin a where a.account_status='suspended' and a.suspension_type='permanent'),coalesce((select sum(g.games_played) from public.bella_game_scores g),0),coalesce((select sum(g.total_correct) from public.bella_game_scores g),0),coalesce((select sum(g.total_answers) from public.bella_game_scores g),0),coalesce((select round(100.0*sum(g.total_correct)/nullif(sum(g.total_answers),0),1) from public.bella_game_scores g),0),coalesce((select u.requests from public.bella_ai_daily_usage u where u.usage_day=current_date),0),(select count(*) from public.bella_broadcasts b where b.enabled and b.starts_at<=now() and (b.expires_at is null or b.expires_at>now())),(select count(*) from public.bella_user_gifts g where g.created_at>=current_date),(select count(*) from public.bella_content_items x where x.status='pending'),(select count(*) from public.bella_content_items x where x.status='approved' and x.enabled=true); end $$;

create or replace function public.bella_public_config() returns table(live_web_enabled boolean,games_enabled boolean,radar_enabled boolean,maintenance_enabled boolean,announcement text,leaderboard_enabled boolean,content_ai_enabled boolean,wisdom_game_enabled boolean,proverb_game_enabled boolean,rumor_list_enabled boolean,box_game_enabled boolean,kuwait_quiz_enabled boolean,updated_at timestamptz) language sql stable security definer set search_path='' as $$ select c.live_web_enabled,c.games_enabled,c.radar_enabled,(c.emergency_lockdown or c.maintenance_enabled or (c.scheduled_maintenance_start is not null and c.scheduled_maintenance_end is not null and now()>=c.scheduled_maintenance_start and now()<c.scheduled_maintenance_end)),case when c.emergency_lockdown then c.lockdown_message when c.scheduled_maintenance_start is not null and c.scheduled_maintenance_end is not null and now()>=c.scheduled_maintenance_start and now()<c.scheduled_maintenance_end and c.scheduled_maintenance_message<>'' then c.scheduled_maintenance_message when c.scheduled_announcement_start is not null and c.scheduled_announcement_end is not null and now()>=c.scheduled_announcement_start and now()<c.scheduled_announcement_end and c.scheduled_announcement<>'' then c.scheduled_announcement else c.announcement end,c.leaderboard_enabled,c.content_ai_enabled,c.wisdom_game_enabled,c.proverb_game_enabled,c.rumor_list_enabled,c.box_game_enabled,c.kuwait_quiz_enabled,c.updated_at from public.bella_app_config c where c.id=1 $$;

create or replace function public.bella_public_config_v3() returns table(live_web_enabled boolean,games_enabled boolean,radar_enabled boolean,maintenance_enabled boolean,announcement text,leaderboard_enabled boolean,content_ai_enabled boolean,wisdom_game_enabled boolean,proverb_game_enabled boolean,rumor_list_enabled boolean,box_game_enabled boolean,kuwait_quiz_enabled boolean,chat_ai_enabled boolean,voice_enabled boolean,ai_activities_enabled boolean,moments_enabled boolean,updated_at timestamptz) language sql stable security definer set search_path='' as $$ select c.live_web_enabled,c.games_enabled,c.radar_enabled,(c.emergency_lockdown or c.maintenance_enabled or (c.scheduled_maintenance_start is not null and c.scheduled_maintenance_end is not null and now()>=c.scheduled_maintenance_start and now()<c.scheduled_maintenance_end)),case when c.emergency_lockdown then c.lockdown_message when c.scheduled_maintenance_start is not null and c.scheduled_maintenance_end is not null and now()>=c.scheduled_maintenance_start and now()<c.scheduled_maintenance_end and c.scheduled_maintenance_message<>'' then c.scheduled_maintenance_message when c.scheduled_announcement_start is not null and c.scheduled_announcement_end is not null and now()>=c.scheduled_announcement_start and now()<c.scheduled_announcement_end and c.scheduled_announcement<>'' then c.scheduled_announcement else c.announcement end,c.leaderboard_enabled,c.content_ai_enabled,c.wisdom_game_enabled,c.proverb_game_enabled,c.rumor_list_enabled,c.box_game_enabled,c.kuwait_quiz_enabled,c.chat_ai_enabled,c.voice_enabled,c.ai_activities_enabled,c.moments_enabled,c.updated_at from public.bella_app_config c where c.id=1 $$;

create or replace function public.bella_claim_ai_request(p_kind text) returns table(allowed boolean,reason text,used integer,daily_limit integer,live_web_enabled boolean,maintenance_enabled boolean) language plpgsql security definer set search_path='' as $$
declare kind text:=lower(trim(coalesce(p_kind,'chat'))); cfg public.bella_app_config%rowtype; current_used integer:=0; maintenance_now boolean:=false;
begin if kind not in ('chat','live_web','voice','activity') then kind:='chat'; end if; perform pg_advisory_xact_lock(hashtext('bella_ai_daily_'||current_date::text)::bigint); select * into cfg from public.bella_app_config where id=1; maintenance_now:=cfg.emergency_lockdown or cfg.maintenance_enabled or (cfg.scheduled_maintenance_start is not null and cfg.scheduled_maintenance_end is not null and now()>=cfg.scheduled_maintenance_start and now()<cfg.scheduled_maintenance_end); select coalesce(u.requests,0) into current_used from public.bella_ai_daily_usage u where u.usage_day=current_date; if maintenance_now then return query select false,'maintenance'::text,current_used,cfg.ai_daily_limit,cfg.live_web_enabled,maintenance_now; return; end if; if kind='live_web' and not cfg.live_web_enabled then return query select false,'live_web_disabled'::text,current_used,cfg.ai_daily_limit,cfg.live_web_enabled,maintenance_now; return; end if; if kind='chat' and not cfg.chat_ai_enabled then return query select false,'chat_disabled'::text,current_used,cfg.ai_daily_limit,cfg.live_web_enabled,maintenance_now; return; end if; if kind='voice' and not cfg.voice_enabled then return query select false,'voice_disabled'::text,current_used,cfg.ai_daily_limit,cfg.live_web_enabled,maintenance_now; return; end if; if kind='activity' and not cfg.ai_activities_enabled then return query select false,'activity_disabled'::text,current_used,cfg.ai_daily_limit,cfg.live_web_enabled,maintenance_now; return; end if; if cfg.ai_daily_limit>0 and current_used>=cfg.ai_daily_limit then return query select false,'daily_limit'::text,current_used,cfg.ai_daily_limit,cfg.live_web_enabled,maintenance_now; return; end if; insert into public.bella_ai_daily_usage(usage_day,requests,chat_requests,live_web_requests,updated_at) values(current_date,1,case when kind='chat' then 1 else 0 end,case when kind='live_web' then 1 else 0 end,now()) on conflict(usage_day) do update set requests=public.bella_ai_daily_usage.requests+1,chat_requests=public.bella_ai_daily_usage.chat_requests+case when kind='chat' then 1 else 0 end,live_web_requests=public.bella_ai_daily_usage.live_web_requests+case when kind='live_web' then 1 else 0 end,updated_at=now() returning requests into current_used; return query select true,'ok'::text,current_used,cfg.ai_daily_limit,cfg.live_web_enabled,maintenance_now; end $$;

revoke all on function public.bella_owner_set_ban(uuid,integer,boolean,text) from public,anon; grant execute on function public.bella_owner_set_ban(uuid,integer,boolean,text) to authenticated;
revoke all on function public.bella_owner_unban(uuid,text) from public,anon; grant execute on function public.bella_owner_unban(uuid,text) to authenticated;
revoke all on function public.bella_owner_set_progress(uuid,integer,integer,text) from public,anon; grant execute on function public.bella_owner_set_progress(uuid,integer,integer,text) to authenticated;
revoke all on function public.bella_owner_adjust_xp(uuid,integer,text) from public,anon; grant execute on function public.bella_owner_adjust_xp(uuid,integer,text) to authenticated;
revoke all on function public.bella_owner_schedule_maintenance(timestamptz,timestamptz,text) from public,anon; grant execute on function public.bella_owner_schedule_maintenance(timestamptz,timestamptz,text) to authenticated;
revoke all on function public.bella_owner_schedule_announcement(text,timestamptz,timestamptz) from public,anon; grant execute on function public.bella_owner_schedule_announcement(text,timestamptz,timestamptz) to authenticated;
revoke all on function public.bella_owner_clear_schedule(text) from public,anon; grant execute on function public.bella_owner_clear_schedule(text) to authenticated;
revoke all on function public.bella_owner_create_broadcast(text,text,text,timestamptz,timestamptz) from public,anon; grant execute on function public.bella_owner_create_broadcast(text,text,text,timestamptz,timestamptz) to authenticated;
revoke all on function public.bella_public_broadcasts() from public; grant execute on function public.bella_public_broadcasts() to anon,authenticated;
revoke all on function public.bella_owner_send_gift(uuid,text,text,integer) from public,anon; grant execute on function public.bella_owner_send_gift(uuid,text,text,integer) to authenticated;
revoke all on function public.bella_my_gifts(integer) from public,anon; grant execute on function public.bella_my_gifts(integer) to authenticated;
revoke all on function public.bella_mark_gift_viewed(bigint) from public,anon; grant execute on function public.bella_mark_gift_viewed(bigint) to authenticated;
revoke all on function public.bella_owner_kill_switch(boolean,text) from public,anon; grant execute on function public.bella_owner_kill_switch(boolean,text) to authenticated;
revoke all on function public.bella_owner_ops_state() from public,anon; grant execute on function public.bella_owner_ops_state() to authenticated;
revoke all on function public.bella_owner_dashboard_v4(integer) from public,anon; grant execute on function public.bella_owner_dashboard_v4(integer) to authenticated;
revoke all on function public.bella_public_config() from public; grant execute on function public.bella_public_config() to anon,authenticated;
revoke all on function public.bella_public_config_v3() from public; grant execute on function public.bella_public_config_v3() to anon,authenticated;
