-- Bella v20 Ops OS
-- Backward-compatible operations layer: tri-state flags, persona tuning,
-- seasons/badges, user 360 + memory tools, airdrops and safe audit rollback.

alter table public.bella_admin_audit
  add column if not exists rolled_back_at timestamptz,
  add column if not exists rolled_back_by uuid references auth.users(id) on delete set null;

create table if not exists public.bella_feature_flags (
  feature_key text primary key,
  mode text not null default 'on' check (mode in ('off','beta','on')),
  label text not null default '',
  note text not null default '',
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);
alter table public.bella_feature_flags enable row level security;
revoke all on table public.bella_feature_flags from anon, authenticated;

insert into public.bella_feature_flags(feature_key,mode,label,note)
select * from (
  values
    ('leaderboard', case when (select leaderboard_enabled from public.bella_app_config where id=1) then 'on' else 'off' end, 'لوحة الترتيب', 'الترتيب العام والموسمي'),
    ('content_ai', case when (select content_ai_enabled from public.bella_app_config where id=1) then 'on' else 'off' end, 'AI للمحتوى', 'توليد ومراجعة المحتوى'),
    ('wisdom_game', case when (select wisdom_game_enabled from public.bella_app_config where id=1) then 'on' else 'off' end, 'حكمة اليوم', 'لعبة حكمة اليوم'),
    ('proverb_game', case when (select proverb_game_enabled from public.bella_app_config where id=1) then 'on' else 'off' end, 'كمّل المثل', 'لعبة الأمثال'),
    ('rumor_list', case when (select rumor_list_enabled from public.bella_app_config where id=1) then 'on' else 'off' end, 'قائمة الإشاعات', 'رادار الإشاعات'),
    ('box_game', case when (select box_game_enabled from public.bella_app_config where id=1) then 'on' else 'off' end, 'شنو بالصندوق', 'لعبة الصندوق'),
    ('kuwait_quiz', case when (select kuwait_quiz_enabled from public.bella_app_config where id=1) then 'on' else 'off' end, 'التحدي الكويتي', 'أسئلة الكويت'),
    ('chat_ai', case when (select chat_ai_enabled from public.bella_app_config where id=1) then 'on' else 'off' end, 'شات AI', 'المحادثة الذكية'),
    ('voice', case when (select voice_enabled from public.bella_app_config where id=1) then 'on' else 'off' end, 'الصوت', 'صوت بيلا'),
    ('ai_activities', case when (select ai_activities_enabled from public.bella_app_config where id=1) then 'on' else 'off' end, 'فعاليات AI', 'تحديات الذكاء الاصطناعي'),
    ('moments', case when (select moments_enabled from public.bella_app_config where id=1) then 'on' else 'off' end, 'لقطات بيلا', 'المومنتس والقطات')
) as seed(feature_key,mode,label,note)
on conflict (feature_key) do nothing;

create table if not exists public.bella_persona_runtime (
  id smallint primary key default 1 check (id=1),
  enabled boolean not null default true,
  system_overlay text not null default '',
  brevity text not null default 'medium' check (brevity in ('short','medium','long')),
  humor smallint not null default 1 check (humor between 0 and 3),
  warmth smallint not null default 1 check (warmth between 0 and 3),
  directness numeric(3,2) not null default 0.35 check (directness between 0 and 1),
  dialect numeric(3,2) not null default 0.80 check (dialect between 0 and 1),
  blocked_phrases jsonb not null default '[]'::jsonb,
  revision integer not null default 1,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);
alter table public.bella_persona_runtime enable row level security;
revoke all on table public.bella_persona_runtime from anon, authenticated;
insert into public.bella_persona_runtime(id) values(1) on conflict(id) do nothing;

create table if not exists public.bella_seasons (
  id bigint generated by default as identity primary key,
  name text not null,
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  status text not null default 'active' check (status in ('active','closed')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  closed_at timestamptz
);
create unique index if not exists bella_seasons_one_active_idx
  on public.bella_seasons((status)) where status='active';
alter table public.bella_seasons enable row level security;
revoke all on table public.bella_seasons from anon, authenticated;

insert into public.bella_seasons(name,status)
select 'الموسم الأول','active'
where not exists(select 1 from public.bella_seasons where status='active');

create table if not exists public.bella_badges (
  badge_key text primary key,
  title text not null,
  icon text not null default '🏅',
  description text not null default '',
  priority integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
alter table public.bella_badges enable row level security;
revoke all on table public.bella_badges from anon, authenticated;

insert into public.bella_badges(badge_key,title,icon,description,priority) values
('alnawkhadha','النوخذة','⚓','بطل موسم بيلا',100),
('alsirdal','السردال','🌊','المركز الثاني في الموسم',90),
('raei_alfazaa','راعي الفزعة','🤝','نشاط وتفاعل مميز',70),
('hafeth_aldira','حافظ الديرة','🇰🇼','معرفة مميزة بالديرة',65),
('saffah_alnuqat','سفاح النقاط','🔥','جامع نقاط شرس',60),
('raei_qaz','راعي قز','🚗','من أهل القز والفعاليات',50),
('diwaniya','ديوانية متنقلة','🛋️','سوالف وتفاعل عالي',45),
('almrawweg','المروّق','😎','مزاج رايق',40),
('raei_albisht','راعي البشت','🧥','وسام تقدير خاص',35),
('altaj','التاج','👑','وسام ملكي خاص',110)
on conflict (badge_key) do update
set title=excluded.title, icon=excluded.icon, description=excluded.description,
    priority=excluded.priority, active=true;

create table if not exists public.bella_user_badges (
  user_id uuid not null references auth.users(id) on delete cascade,
  badge_key text not null references public.bella_badges(badge_key) on delete cascade,
  season_id bigint references public.bella_seasons(id) on delete set null,
  awarded_by uuid references auth.users(id) on delete set null,
  awarded_at timestamptz not null default now(),
  note text not null default '',
  primary key(user_id,badge_key,awarded_at)
);
create index if not exists bella_user_badges_user_idx on public.bella_user_badges(user_id,awarded_at desc);
alter table public.bella_user_badges enable row level security;
revoke all on table public.bella_user_badges from anon, authenticated;

create table if not exists public.bella_season_winners (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.bella_seasons(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  place smallint not null check (place between 1 and 10),
  score bigint not null default 0,
  display_name text not null default 'لاعب',
  created_at timestamptz not null default now(),
  unique(season_id,place),
  unique(season_id,user_id)
);
alter table public.bella_season_winners enable row level security;
revoke all on table public.bella_season_winners from anon, authenticated;

alter table public.bella_game_scores
  add column if not exists season_id bigint references public.bella_seasons(id) on delete set null,
  add column if not exists season_score bigint not null default 0;

update public.bella_game_scores g
set season_id = s.id
from public.bella_seasons s
where s.status='active' and g.season_id is null;

create index if not exists bella_game_scores_season_rank_idx
  on public.bella_game_scores(season_id,season_score desc,updated_at asc);

create or replace function public.bella_public_ops_v20()
returns table(
  feature_flags jsonb,
  persona_style jsonb,
  current_season jsonb
)
language sql stable security definer set search_path=''
as $$
  with me as (
    select public.is_bella_owner() as is_owner
  ),
  flags as (
    select coalesce(jsonb_object_agg(
      f.feature_key,
      jsonb_build_object(
        'mode', f.mode,
        'effective', case when f.mode='on' then true when f.mode='beta' then (select is_owner from me) else false end,
        'label', f.label,
        'note', f.note
      )
    ), '{}'::jsonb) value
    from public.bella_feature_flags f
  ),
  persona as (
    select jsonb_build_object(
      'enabled',p.enabled,'brevity',p.brevity,'humor',p.humor,'warmth',p.warmth,
      'directness',p.directness,'dialect',p.dialect,'revision',p.revision,'updated_at',p.updated_at
    ) value
    from public.bella_persona_runtime p where p.id=1
  ),
  season as (
    select jsonb_build_object(
      'id',s.id,'name',s.name,'starts_at',s.starts_at,'ends_at',s.ends_at,'status',s.status
    ) value
    from public.bella_seasons s where s.status='active' order by s.id desc limit 1
  )
  select (select value from flags),
         coalesce((select value from persona),'{}'::jsonb),
         coalesce((select value from season),'{}'::jsonb);
$$;
revoke all on function public.bella_public_ops_v20() from public;
grant execute on function public.bella_public_ops_v20() to anon, authenticated;

create or replace function public.bella_owner_ops_v20()
returns table(feature_flags jsonb, persona jsonb, current_season jsonb)
language plpgsql stable security definer set search_path=''
as $$
begin
  if not public.is_bella_owner() then
    raise exception 'owner access required' using errcode='42501';
  end if;
  return query
  select
    coalesce((select jsonb_object_agg(f.feature_key,to_jsonb(f)-'feature_key') from public.bella_feature_flags f),'{}'::jsonb),
    coalesce((select to_jsonb(p) from public.bella_persona_runtime p where p.id=1),'{}'::jsonb),
    coalesce((select to_jsonb(s) from public.bella_seasons s where s.status='active' order by s.id desc limit 1),'{}'::jsonb);
end
$$;
revoke all on function public.bella_owner_ops_v20() from public, anon;
grant execute on function public.bella_owner_ops_v20() to authenticated;

create or replace function public.bella_owner_set_feature_flag(p_key text,p_mode text,p_note text default null)
returns jsonb
language plpgsql security definer set search_path=''
as $$
declare
  actor uuid:=auth.uid();
  k text:=lower(trim(coalesce(p_key,'')));
  m text:=lower(trim(coalesce(p_mode,'')));
  oldv jsonb;
  rowv jsonb;
begin
  if not public.is_bella_owner() then raise exception 'owner access required' using errcode='42501'; end if;
  if m not in ('off','beta','on') then raise exception 'invalid mode' using errcode='22023'; end if;
  select to_jsonb(f) into oldv from public.bella_feature_flags f where f.feature_key=k for update;
  if oldv is null then raise exception 'unknown feature flag' using errcode='22023'; end if;

  update public.bella_feature_flags
  set mode=m, note=case when p_note is null then note else left(trim(p_note),300) end,
      updated_by=actor, updated_at=now()
  where feature_key=k
  returning jsonb_build_object(
    'feature_key',feature_key,'mode',mode,'label',label,'note',note,
    'updated_by',updated_by,'updated_at',updated_at
  ) into rowv;

  update public.bella_app_config set
    leaderboard_enabled=case when k='leaderboard' then m<>'off' else leaderboard_enabled end,
    content_ai_enabled=case when k='content_ai' then m<>'off' else content_ai_enabled end,
    wisdom_game_enabled=case when k='wisdom_game' then m<>'off' else wisdom_game_enabled end,
    proverb_game_enabled=case when k='proverb_game' then m<>'off' else proverb_game_enabled end,
    rumor_list_enabled=case when k='rumor_list' then m<>'off' else rumor_list_enabled end,
    box_game_enabled=case when k='box_game' then m<>'off' else box_game_enabled end,
    kuwait_quiz_enabled=case when k='kuwait_quiz' then m<>'off' else kuwait_quiz_enabled end,
    chat_ai_enabled=case when k='chat_ai' then m<>'off' else chat_ai_enabled end,
    voice_enabled=case when k='voice' then m<>'off' else voice_enabled end,
    ai_activities_enabled=case when k='ai_activities' then m<>'off' else ai_activities_enabled end,
    moments_enabled=case when k='moments' then m<>'off' else moments_enabled end,
    updated_by=actor,updated_at=now()
  where id=1;

  insert into public.bella_admin_audit(actor_user_id,target_user_id,action,old_value,new_value,reason)
  values(actor,actor,'v20_feature_flag',coalesce(oldv,'{}'::jsonb),coalesce(rowv,'{}'::jsonb),left(trim(coalesce(p_note,'')),240));
  return rowv;
end
$$;
revoke all on function public.bella_owner_set_feature_flag(text,text,text) from public,anon;
grant execute on function public.bella_owner_set_feature_flag(text,text,text) to authenticated;

create or replace function public.bella_owner_update_persona_v20(
  p_enabled boolean,
  p_system_overlay text,
  p_brevity text,
  p_humor integer,
  p_warmth integer,
  p_directness numeric,
  p_dialect numeric,
  p_blocked_phrases jsonb default '[]'::jsonb
) returns jsonb
language plpgsql security definer set search_path=''
as $$
declare
  actor uuid:=auth.uid();
  oldv jsonb;
  rowv jsonb;
  b text:=lower(trim(coalesce(p_brevity,'medium')));
begin
  if not public.is_bella_owner() then raise exception 'owner access required' using errcode='42501'; end if;
  if b not in ('short','medium','long') then raise exception 'invalid brevity' using errcode='22023'; end if;
  if jsonb_typeof(coalesce(p_blocked_phrases,'[]'::jsonb))<>'array' then raise exception 'blocked phrases must be an array' using errcode='22023'; end if;
  select to_jsonb(p) into oldv from public.bella_persona_runtime p where p.id=1 for update;
  update public.bella_persona_runtime
    set enabled=coalesce(p_enabled,true),
        system_overlay=left(trim(coalesce(p_system_overlay,'')),6000),
        brevity=b,
        humor=greatest(0,least(coalesce(p_humor,1),3)),
        warmth=greatest(0,least(coalesce(p_warmth,1),3)),
        directness=greatest(0::numeric,least(coalesce(p_directness,.35),1::numeric)),
        dialect=greatest(0::numeric,least(coalesce(p_dialect,.80),1::numeric)),
        blocked_phrases=p_blocked_phrases,
        revision=revision+1,updated_by=actor,updated_at=now()
    where id=1
    returning jsonb_build_object(
      'id',id,'enabled',enabled,'system_overlay',system_overlay,'brevity',brevity,
      'humor',humor,'warmth',warmth,'directness',directness,'dialect',dialect,
      'blocked_phrases',blocked_phrases,'revision',revision,'updated_by',updated_by,'updated_at',updated_at
    ) into rowv;
  insert into public.bella_admin_audit(actor_user_id,target_user_id,action,old_value,new_value,reason)
  values(actor,actor,'v20_persona_update',coalesce(oldv,'{}'::jsonb),coalesce(rowv,'{}'::jsonb),'Bella Persona Tuner v20');
  return rowv;
end
$$;
revoke all on function public.bella_owner_update_persona_v20(boolean,text,text,integer,integer,numeric,numeric,jsonb) from public,anon;
grant execute on function public.bella_owner_update_persona_v20(boolean,text,text,integer,integer,numeric,numeric,jsonb) to authenticated;

create or replace function public.bella_owner_user_360_v20(p_user_id uuid)
returns jsonb
language plpgsql stable security definer set search_path=''
as $$
declare outv jsonb;
begin
  if not public.is_bella_owner() then raise exception 'owner access required' using errcode='42501'; end if;
  if p_user_id is null then raise exception 'user required' using errcode='22023'; end if;
  select jsonb_build_object(
    'profile',to_jsonb(p),
    'admin',coalesce(to_jsonb(a),'{}'::jsonb),
    'games',coalesce(to_jsonb(g),'{}'::jsonb),
    'memory_count',(select count(*) from public.bella_memories m where m.user_id=p_user_id and m.deleted_at is null),
    'gift_count',(select count(*) from public.bella_user_gifts ug where ug.user_id=p_user_id),
    'badges',coalesce((select jsonb_agg(jsonb_build_object('badge_key',ub.badge_key,'title',b.title,'icon',b.icon,'awarded_at',ub.awarded_at,'note',ub.note) order by ub.awarded_at desc)
                       from public.bella_user_badges ub join public.bella_badges b on b.badge_key=ub.badge_key where ub.user_id=p_user_id),'[]'::jsonb)
  ) into outv
  from public.bella_profiles p
  left join public.bella_account_admin a on a.user_id=p.user_id
  left join public.bella_game_scores g on g.user_id=p.user_id
  where p.user_id=p_user_id;
  if outv is null then raise exception 'user not found' using errcode='22023'; end if;
  return outv;
end
$$;
revoke all on function public.bella_owner_user_360_v20(uuid) from public,anon;
grant execute on function public.bella_owner_user_360_v20(uuid) to authenticated;

create or replace function public.bella_owner_memories_v20(p_user_id uuid,p_include_deleted boolean default false)
returns table(id uuid,memory_key text,memory_text text,category text,source text,created_at timestamptz,updated_at timestamptz,deleted_at timestamptz)
language plpgsql stable security definer set search_path=''
as $$
begin
  if not public.is_bella_owner() then raise exception 'owner access required' using errcode='42501'; end if;
  return query
  select m.id,m.memory_key,m.memory_text,m.category,m.source,m.created_at,m.updated_at,m.deleted_at
  from public.bella_memories m
  where m.user_id=p_user_id and (coalesce(p_include_deleted,false) or m.deleted_at is null)
  order by m.updated_at desc
  limit 300;
end
$$;
revoke all on function public.bella_owner_memories_v20(uuid,boolean) from public,anon;
grant execute on function public.bella_owner_memories_v20(uuid,boolean) to authenticated;

create or replace function public.bella_owner_update_memory_v20(p_memory_id uuid,p_text text,p_category text default null)
returns jsonb
language plpgsql security definer set search_path=''
as $$
declare actor uuid:=auth.uid(); oldv jsonb; rowv jsonb; owner_uid uuid;
begin
  if not public.is_bella_owner() then raise exception 'owner access required' using errcode='42501'; end if;
  select m.user_id,to_jsonb(m) into owner_uid,oldv from public.bella_memories m where m.id=p_memory_id for update;
  if oldv is null then raise exception 'memory not found' using errcode='22023'; end if;
  update public.bella_memories
  set memory_text=left(trim(coalesce(p_text,'')),2000),
      category=case when p_category is null then category else left(trim(p_category),80) end,
      updated_at=now(),deleted_at=null
  where id=p_memory_id returning to_jsonb(bella_memories) into rowv;
  insert into public.bella_admin_audit(actor_user_id,target_user_id,action,old_value,new_value,reason)
  values(actor,owner_uid,'v20_memory_update',oldv,rowv,'Memory Inspector');
  return rowv;
end
$$;
revoke all on function public.bella_owner_update_memory_v20(uuid,text,text) from public,anon;
grant execute on function public.bella_owner_update_memory_v20(uuid,text,text) to authenticated;

create or replace function public.bella_owner_delete_memory_v20(p_memory_id uuid,p_reason text default null)
returns boolean
language plpgsql security definer set search_path=''
as $$
declare actor uuid:=auth.uid(); oldv jsonb; owner_uid uuid;
begin
  if not public.is_bella_owner() then raise exception 'owner access required' using errcode='42501'; end if;
  select m.user_id,to_jsonb(m) into owner_uid,oldv from public.bella_memories m where m.id=p_memory_id for update;
  if oldv is null then raise exception 'memory not found' using errcode='22023'; end if;
  update public.bella_memories set deleted_at=now(),updated_at=now() where id=p_memory_id;
  insert into public.bella_admin_audit(actor_user_id,target_user_id,action,old_value,new_value,reason)
  values(actor,owner_uid,'v20_memory_delete',oldv,jsonb_build_object('id',p_memory_id,'deleted_at',now()),left(trim(coalesce(p_reason,'')),240));
  return true;
end
$$;
revoke all on function public.bella_owner_delete_memory_v20(uuid,text) from public,anon;
grant execute on function public.bella_owner_delete_memory_v20(uuid,text) to authenticated;

create or replace function public.bella_owner_award_badge_v20(p_user_id uuid,p_badge_key text,p_note text default null)
returns jsonb
language plpgsql security definer set search_path=''
as $$
declare actor uuid:=auth.uid(); sid bigint; rowv jsonb;
begin
  if not public.is_bella_owner() then raise exception 'owner access required' using errcode='42501'; end if;
  if not exists(select 1 from public.bella_profiles p where p.user_id=p_user_id) then raise exception 'user not found' using errcode='22023'; end if;
  if not exists(select 1 from public.bella_badges b where b.badge_key=p_badge_key and b.active) then raise exception 'badge not found' using errcode='22023'; end if;
  select s.id into sid from public.bella_seasons s where s.status='active' order by s.id desc limit 1;
  insert into public.bella_user_badges(user_id,badge_key,season_id,awarded_by,note)
  values(p_user_id,p_badge_key,sid,actor,left(trim(coalesce(p_note,'')),240))
  returning jsonb_build_object('user_id',user_id,'badge_key',badge_key,'season_id',season_id,'awarded_at',awarded_at) into rowv;
  insert into public.bella_admin_audit(actor_user_id,target_user_id,action,old_value,new_value,reason)
  values(actor,p_user_id,'v20_award_badge','{}'::jsonb,rowv,left(trim(coalesce(p_note,'')),240));
  return rowv;
end
$$;
revoke all on function public.bella_owner_award_badge_v20(uuid,text,text) from public,anon;
grant execute on function public.bella_owner_award_badge_v20(uuid,text,text) to authenticated;

create or replace function public.bella_my_badges_v20()
returns table(badge_key text,title text,icon text,description text,priority integer,awarded_at timestamptz,note text)
language sql stable security definer set search_path=''
as $$
  select b.badge_key,b.title,b.icon,b.description,b.priority,ub.awarded_at,ub.note
  from public.bella_user_badges ub
  join public.bella_badges b on b.badge_key=ub.badge_key
  where ub.user_id=auth.uid() and b.active
  order by b.priority desc,ub.awarded_at desc;
$$;
revoke all on function public.bella_my_badges_v20() from public,anon;
grant execute on function public.bella_my_badges_v20() to authenticated;

create or replace function public.bella_season_leaderboard_v20(p_limit integer default 20)
returns table(user_id uuid,display_name text,season_score bigint,place bigint)
language sql stable security definer set search_path=''
as $$
  with current_s as (
    select s.id from public.bella_seasons s where s.status='active' order by s.id desc limit 1
  ), ranked as (
    select g.user_id,g.display_name,g.season_score,
           row_number() over(order by g.season_score desc,g.updated_at asc,g.user_id) place
    from public.bella_game_scores g
    left join public.bella_account_admin a on a.user_id=g.user_id
    where g.season_id=(select id from current_s)
      and g.season_score>0
      and coalesce(a.leaderboard_blocked,false)=false
  )
  select r.user_id,r.display_name,r.season_score,r.place
  from ranked r order by r.place
  limit greatest(1,least(coalesce(p_limit,20),100));
$$;
revoke all on function public.bella_season_leaderboard_v20(integer) from public;
grant execute on function public.bella_season_leaderboard_v20(integer) to anon,authenticated;

create or replace function public.bella_owner_close_season_v20(p_next_name text default null)
returns jsonb
language plpgsql security definer set search_path=''
as $$
declare
  actor uuid:=auth.uid();
  sid bigint;
  sname text;
  nextid bigint;
  nextname text;
  winner record;
  cnt integer:=0;
begin
  if not public.is_bella_owner() then raise exception 'owner access required' using errcode='42501'; end if;
  select s.id,s.name into sid,sname from public.bella_seasons s where s.status='active' order by s.id desc limit 1 for update;
  if sid is null then raise exception 'no active season' using errcode='22023'; end if;

  delete from public.bella_season_winners where season_id=sid;
  for winner in
    select g.user_id,g.display_name,g.season_score,
           row_number() over(order by g.season_score desc,g.updated_at asc,g.user_id) place
    from public.bella_game_scores g
    left join public.bella_account_admin a on a.user_id=g.user_id
    where g.season_id=sid and g.season_score>0 and coalesce(a.leaderboard_blocked,false)=false
    order by g.season_score desc,g.updated_at asc,g.user_id
    limit 3
  loop
    insert into public.bella_season_winners(season_id,user_id,place,score,display_name)
    values(sid,winner.user_id,winner.place,winner.season_score,winner.display_name);
    if winner.place=1 then
      insert into public.bella_user_badges(user_id,badge_key,season_id,awarded_by,note)
      values(winner.user_id,'alnawkhadha',sid,actor,'بطل '||sname);
    elsif winner.place=2 then
      insert into public.bella_user_badges(user_id,badge_key,season_id,awarded_by,note)
      values(winner.user_id,'alsirdal',sid,actor,'وصيف '||sname);
    elsif winner.place=3 then
      insert into public.bella_user_badges(user_id,badge_key,season_id,awarded_by,note)
      values(winner.user_id,'raei_alfazaa',sid,actor,'المركز الثالث في '||sname);
    end if;
    cnt:=cnt+1;
  end loop;

  update public.bella_seasons set status='closed',ends_at=coalesce(ends_at,now()),closed_at=now() where id=sid;
  nextname:=nullif(left(trim(coalesce(p_next_name,'')),100),'');
  if nextname is null then nextname:='الموسم '||(sid+1)::text; end if;
  insert into public.bella_seasons(name,status,created_by) values(nextname,'active',actor) returning id into nextid;
  update public.bella_game_scores set season_id=nextid,season_score=0,updated_at=now();

  insert into public.bella_admin_audit(actor_user_id,target_user_id,action,old_value,new_value,reason)
  values(actor,actor,'v20_close_season',jsonb_build_object('season_id',sid,'name',sname),
         jsonb_build_object('next_season_id',nextid,'next_name',nextname,'winners',cnt),'Season rollover');

  return jsonb_build_object('closed_season_id',sid,'closed_name',sname,'next_season_id',nextid,'next_name',nextname,'winners_saved',cnt);
end
$$;
revoke all on function public.bella_owner_close_season_v20(text) from public,anon;
grant execute on function public.bella_owner_close_season_v20(text) to authenticated;

create or replace function public.bella_owner_global_drop_v20(
  p_xp integer default 0,
  p_badge_key text default null,
  p_label text default 'هدية جماعية من بيلا 🎁',
  p_message text default null,
  p_reason text default null
) returns jsonb
language plpgsql security definer set search_path=''
as $$
declare
  actor uuid:=auth.uid();
  amount integer:=greatest(0,least(coalesce(p_xp,0),5000));
  badge text:=nullif(trim(coalesce(p_badge_key,'')),'');
  affected integer:=0;
  gifted integer:=0;
begin
  if not public.is_bella_owner() then raise exception 'owner access required' using errcode='42501'; end if;
  if amount=0 and badge is null and trim(coalesce(p_message,''))='' then raise exception 'empty drop' using errcode='22023'; end if;
  if badge is not null and not exists(select 1 from public.bella_badges b where b.badge_key=badge and b.active) then raise exception 'badge not found' using errcode='22023'; end if;

  if amount>0 then
    update public.bella_profiles p
      set xp=least(1000000,p.xp+amount),
          level=greatest(1,floor(least(1000000,p.xp+amount)/100.0)::integer+1),
          updated_at=now()
    where not exists(
      select 1 from public.bella_account_admin a
      where a.user_id=p.user_id and a.account_status='suspended'
        and not (a.suspension_type='temporary' and a.suspended_until is not null and a.suspended_until<=now())
    );
    get diagnostics affected=row_count;
  end if;

  if trim(coalesce(p_message,''))<>'' or amount>0 then
    insert into public.bella_user_gifts(user_id,gift_type,label,message,xp_amount,created_by)
    select p.user_id,case when amount>0 then 'bonus' else 'gift' end,
           left(trim(coalesce(p_label,'هدية جماعية من بيلا 🎁')),120),
           left(trim(coalesce(p_message,'')),500),amount,actor
    from public.bella_profiles p
    where not exists(
      select 1 from public.bella_account_admin a
      where a.user_id=p.user_id and a.account_status='suspended'
        and not (a.suspension_type='temporary' and a.suspended_until is not null and a.suspended_until<=now())
    );
    get diagnostics gifted=row_count;
    update public.bella_profiles p
      set gifts=p.gifts+1,updated_at=now()
    where not exists(
      select 1 from public.bella_account_admin a
      where a.user_id=p.user_id and a.account_status='suspended'
        and not (a.suspension_type='temporary' and a.suspended_until is not null and a.suspended_until<=now())
    );
  end if;

  if badge is not null then
    insert into public.bella_user_badges(user_id,badge_key,season_id,awarded_by,note)
    select p.user_id,badge,(select s.id from public.bella_seasons s where s.status='active' order by s.id desc limit 1),
           actor,left(trim(coalesce(p_reason,'Global Drop')),240)
    from public.bella_profiles p
    where not exists(
      select 1 from public.bella_account_admin a
      where a.user_id=p.user_id and a.account_status='suspended'
        and not (a.suspension_type='temporary' and a.suspended_until is not null and a.suspended_until<=now())
    );
  end if;

  insert into public.bella_admin_audit(actor_user_id,target_user_id,action,old_value,new_value,reason)
  values(actor,actor,'v20_global_drop','{}'::jsonb,
         jsonb_build_object('xp',amount,'badge_key',badge,'profiles',affected,'gifts',gifted),
         left(trim(coalesce(p_reason,'')),240));
  return jsonb_build_object('profiles_updated',affected,'gifts_sent',gifted,'xp_each',amount,'badge_key',badge);
end
$$;
revoke all on function public.bella_owner_global_drop_v20(integer,text,text,text,text) from public,anon;
grant execute on function public.bella_owner_global_drop_v20(integer,text,text,text,text) to authenticated;

create or replace function public.bella_owner_ai_usage_v20(p_days integer default 14)
returns table(usage_day date,requests integer,chat_requests integer,live_web_requests integer,estimated_tokens bigint)
language plpgsql stable security definer set search_path=''
as $$
declare days integer:=greatest(1,least(coalesce(p_days,14),90));
begin
  if not public.is_bella_owner() then raise exception 'owner access required' using errcode='42501'; end if;
  return query
  select u.usage_day,u.requests,u.chat_requests,u.live_web_requests,
         (coalesce(u.chat_requests,0)::bigint*700 + coalesce(u.live_web_requests,0)::bigint*1200) estimated_tokens
  from public.bella_ai_daily_usage u
  where u.usage_day>=current_date-(days-1)
  order by u.usage_day desc;
end
$$;
revoke all on function public.bella_owner_ai_usage_v20(integer) from public,anon;
grant execute on function public.bella_owner_ai_usage_v20(integer) to authenticated;

create or replace function public.bella_owner_audit_v20(p_limit integer default 60,p_offset integer default 0)
returns table(
  id bigint,actor_user_id uuid,target_user_id uuid,target_display_name text,action text,
  old_value jsonb,new_value jsonb,reason text,created_at timestamptz,rolled_back_at timestamptz,
  rollback_available boolean,total_count bigint
)
language plpgsql stable security definer set search_path=''
as $$
declare lim integer:=greatest(1,least(coalesce(p_limit,60),100)); off integer:=greatest(0,coalesce(p_offset,0));
begin
  if not public.is_bella_owner() then raise exception 'owner access required' using errcode='42501'; end if;
  return query
  select a.id,a.actor_user_id,a.target_user_id,coalesce(p.display_name,'مستخدم')::text,a.action,
         a.old_value,a.new_value,a.reason,a.created_at,a.rolled_back_at,
         (a.rolled_back_at is null and a.action in ('v20_feature_flag','v20_persona_update','v20_memory_update','v20_memory_delete')) as rollback_available,
         count(*) over()::bigint
  from public.bella_admin_audit a
  left join public.bella_profiles p on p.user_id=a.target_user_id
  order by a.created_at desc
  limit lim offset off;
end
$$;
revoke all on function public.bella_owner_audit_v20(integer,integer) from public,anon;
grant execute on function public.bella_owner_audit_v20(integer,integer) to authenticated;

create or replace function public.bella_owner_rollback_v20(p_audit_id bigint)
returns boolean
language plpgsql security definer set search_path=''
as $$
declare
  actor uuid:=auth.uid();
  a public.bella_admin_audit%rowtype;
  mid uuid;
begin
  if not public.is_bella_owner() then raise exception 'owner access required' using errcode='42501'; end if;
  select * into a from public.bella_admin_audit where id=p_audit_id for update;
  if a.id is null then raise exception 'audit row not found' using errcode='22023'; end if;
  if a.rolled_back_at is not null then raise exception 'already rolled back' using errcode='22023'; end if;

  if a.action='v20_feature_flag' then
    update public.bella_feature_flags
      set mode=coalesce(a.old_value->>'mode','on'),
          note=coalesce(a.old_value->>'note',''),
          updated_by=actor,updated_at=now()
    where feature_key=a.old_value->>'feature_key';
  elsif a.action='v20_persona_update' then
    update public.bella_persona_runtime set
      enabled=coalesce((a.old_value->>'enabled')::boolean,true),
      system_overlay=coalesce(a.old_value->>'system_overlay',''),
      brevity=coalesce(a.old_value->>'brevity','medium'),
      humor=coalesce((a.old_value->>'humor')::integer,1),
      warmth=coalesce((a.old_value->>'warmth')::integer,1),
      directness=coalesce((a.old_value->>'directness')::numeric,.35),
      dialect=coalesce((a.old_value->>'dialect')::numeric,.80),
      blocked_phrases=coalesce(a.old_value->'blocked_phrases','[]'::jsonb),
      revision=revision+1,updated_by=actor,updated_at=now()
    where id=1;
  elsif a.action in ('v20_memory_update','v20_memory_delete') then
    mid=(a.old_value->>'id')::uuid;
    update public.bella_memories set
      memory_key=coalesce(a.old_value->>'memory_key',memory_key),
      memory_text=coalesce(a.old_value->>'memory_text',memory_text),
      category=coalesce(a.old_value->>'category',category),
      source=coalesce(a.old_value->>'source',source),
      deleted_at=case when a.old_value ? 'deleted_at' and a.old_value->>'deleted_at' is not null then (a.old_value->>'deleted_at')::timestamptz else null end,
      updated_at=now()
    where id=mid;
  else
    raise exception 'rollback not supported for this action' using errcode='22023';
  end if;

  update public.bella_admin_audit set rolled_back_at=now(),rolled_back_by=actor where id=p_audit_id;
  insert into public.bella_admin_audit(actor_user_id,target_user_id,action,old_value,new_value,reason)
  values(actor,a.target_user_id,'v20_rollback',jsonb_build_object('audit_id',p_audit_id,'action',a.action),
         jsonb_build_object('restored',true),'Rollback from Ops OS v20');
  return true;
end
$$;
revoke all on function public.bella_owner_rollback_v20(bigint) from public,anon;
grant execute on function public.bella_owner_rollback_v20(bigint) to authenticated;

-- Harden the game score submission function and add season scoring.
create or replace function public.bella_submit_game_score(
  p_display_name text,
  p_game text,
  p_correct boolean,
  p_points integer,
  p_streak integer,
  p_session_complete boolean default false
) returns public.bella_game_scores
language plpgsql security definer set search_path=''
as $$
declare
  v_uid uuid:=auth.uid();
  v_name text:=left(regexp_replace(coalesce(p_display_name,'لاعب'),'\s+',' ','g'),40);
  v_points integer:=greatest(0,least(coalesce(p_points,0),100));
  v_streak integer:=greatest(0,least(coalesce(p_streak,0),1000));
  v_today date:=current_date;
  v_week date:=date_trunc('week',current_date)::date;
  v_season bigint;
  v_row public.bella_game_scores;
begin
  if v_uid is null then raise exception 'Authentication required' using errcode='42501'; end if;
  if not public.bella_is_account_active() then raise exception 'Account suspended' using errcode='42501'; end if;
  if char_length(trim(v_name))=0 then v_name:='لاعب'; end if;
  select s.id into v_season from public.bella_seasons s where s.status='active' order by s.id desc limit 1;

  insert into public.bella_game_scores as s(
    user_id,display_name,total_correct,total_answers,games_played,best_streak,xp_earned,
    daily_score,daily_date,weekly_score,week_start,season_id,season_score,updated_at
  ) values(
    v_uid,v_name,case when p_correct then 1 else 0 end,1,case when p_session_complete then 1 else 0 end,
    v_streak,v_points,v_points,v_today,v_points,v_week,v_season,v_points,now()
  )
  on conflict(user_id) do update set
    display_name=excluded.display_name,
    total_correct=s.total_correct+case when p_correct then 1 else 0 end,
    total_answers=s.total_answers+1,
    games_played=s.games_played+case when p_session_complete then 1 else 0 end,
    best_streak=greatest(s.best_streak,v_streak),
    xp_earned=s.xp_earned+v_points,
    daily_score=case when s.daily_date=v_today then s.daily_score+v_points else v_points end,
    daily_date=v_today,
    weekly_score=case when s.week_start=v_week then s.weekly_score+v_points else v_points end,
    week_start=v_week,
    season_id=v_season,
    season_score=case when s.season_id=v_season then s.season_score+v_points else v_points end,
    updated_at=now()
  returning * into v_row;
  return v_row;
end
$$;
revoke all on function public.bella_submit_game_score(text,text,boolean,integer,integer,boolean) from public,anon;
grant execute on function public.bella_submit_game_score(text,text,boolean,integer,integer,boolean) to authenticated;
